site_name: Sylvia's website
nav:
  - Home: index.md
  - About me: About-me.md
  - Markdown: markdown_assignment.md
  - Structured Authoring in DITA: Structured-Authoring.md
  - Digital Literacy Narrative and Reflection: Digital-Literacy-Narrative.md
theme: material 
use_directory_urls: false